# Generated by Django 3.1.6 on 2021-02-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome do aluno')),
                ('classe', models.CharField(max_length=20, verbose_name='Classe e Turma')),
                ('valor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mes', models.CharField(choices=[('janeiro', 'janeiro'), ('fevereiro', 'fevereiro'), ('março', 'março')], max_length=20, verbose_name='mês')),
            ],
        ),
    ]
