# Generated by Django 3.1 on 2021-02-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0003_auto_20210203_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagar',
            name='conta',
        ),
    ]
