# Generated by Django 3.1.6 on 2021-02-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0005_pagar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagar',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
